name    'joejulian-nginx'
version '0.0.3'
source 'http://github.com/joejulian/joejulian-nginx'
author 'puppetlabs, Joe Julian <me@joejulian.name>'
license 'Apache License Version 2.0'
summary 'Puppet NGINX management module'
description 'This module can be used for basic NGINX Management'
project_page 'http://github.com/joejulian/joejulian-nginx'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
dependency 'joejulian/yum', '>= 2.0.1'
dependency 'joejulian/logfile', '>= 1.0.0'
